######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 3 17:33:34 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Ball.h GameField.h GameObject.h
SOURCES += Ball.cpp GameField.cpp main.cpp
