######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 23 00:08:38 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Ball.h GameField.h GameObject.h Wall.h
SOURCES += Ball.cpp GameField.cpp main.cpp Wall.cpp
