######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 10 19:02:44 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Ball.h GameField.h GameObject.h
SOURCES += Ball.cpp GameField.cpp main.cpp
